/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RatingStars: typeof import('./src/components/RatingStars.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WatchlistButtons: typeof import('./src/components/WatchlistButtons.vue')['default']
  }
}
